version: "3.6"
services:
  php-apache:
    image: php:8.1-apache
    ports:
      - "7080:80"
    volumes:
      - ./public:/var/www/html
    command:
      [
        "sh",
        "-c",
        "a2dismod alias -f && docker-php-entrypoint apache2-foreground",
      ]
